import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"

export async function POST(request: Request) {
  try {
    const supabase = await createClient()

    // Verify user is authenticated
    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { generationId } = await request.json()

    // Fetch the generation
    const { data: generation, error } = await supabase
      .from("generations")
      .select("*")
      .eq("id", generationId)
      .eq("user_id", user.id)
      .single()

    if (error || !generation) {
      return NextResponse.json({ error: "Generation not found" }, { status: 404 })
    }

    // Generate PDF content as HTML that can be converted to PDF
    const pdfHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${generation.startup_name} - Startup Pitch</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      padding: 60px;
      max-width: 800px;
      margin: 0 auto;
    }
    
    .header {
      text-align: center;
      margin-bottom: 60px;
      padding-bottom: 30px;
      border-bottom: 3px solid ${generation.color_scheme.primary};
    }
    
    .logo {
      font-size: 48px;
      font-weight: bold;
      color: ${generation.color_scheme.primary};
      margin-bottom: 10px;
    }
    
    .tagline {
      font-size: 20px;
      font-style: italic;
      color: #666;
      margin-top: 10px;
    }
    
    .section {
      margin-bottom: 40px;
    }
    
    .section-title {
      font-size: 24px;
      font-weight: bold;
      color: ${generation.color_scheme.primary};
      margin-bottom: 15px;
      padding-bottom: 10px;
      border-bottom: 2px solid #e0e0e0;
    }
    
    .section-content {
      font-size: 16px;
      color: #333;
      line-height: 1.8;
    }
    
    .features-list {
      list-style: none;
      padding-left: 0;
    }
    
    .features-list li {
      padding: 12px 0;
      padding-left: 30px;
      position: relative;
    }
    
    .features-list li:before {
      content: "✓";
      position: absolute;
      left: 0;
      color: ${generation.color_scheme.primary};
      font-weight: bold;
      font-size: 20px;
    }
    
    .color-scheme {
      display: flex;
      gap: 30px;
      margin-top: 20px;
    }
    
    .color-box {
      text-align: center;
    }
    
    .color-swatch {
      width: 100px;
      height: 100px;
      border-radius: 8px;
      margin-bottom: 10px;
      border: 2px solid #e0e0e0;
    }
    
    .color-label {
      font-size: 14px;
      color: #666;
      font-weight: 500;
    }
    
    .footer {
      margin-top: 60px;
      padding-top: 30px;
      border-top: 2px solid #e0e0e0;
      text-align: center;
      color: #999;
      font-size: 14px;
    }
    
    @media print {
      body {
        padding: 40px;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">${generation.startup_name}</div>
    <div class="tagline">${generation.tagline}</div>
  </div>

  <div class="section">
    <h2 class="section-title">Executive Summary</h2>
    <p class="section-content">${generation.description}</p>
  </div>

  <div class="section">
    <h2 class="section-title">Target Audience</h2>
    <p class="section-content">${generation.target_audience}</p>
  </div>

  <div class="section">
    <h2 class="section-title">Key Features</h2>
    <ul class="features-list">
      ${generation.key_features.map((feature: string) => `<li>${feature}</li>`).join("")}
    </ul>
  </div>

  <div class="section">
    <h2 class="section-title">Brand Colors</h2>
    <div class="color-scheme">
      <div class="color-box">
        <div class="color-swatch" style="background-color: ${generation.color_scheme.primary};"></div>
        <div class="color-label">Primary<br>${generation.color_scheme.primary}</div>
      </div>
      <div class="color-box">
        <div class="color-swatch" style="background-color: ${generation.color_scheme.secondary};"></div>
        <div class="color-label">Secondary<br>${generation.color_scheme.secondary}</div>
      </div>
      <div class="color-box">
        <div class="color-swatch" style="background-color: ${generation.color_scheme.accent};"></div>
        <div class="color-label">Accent<br>${generation.color_scheme.accent}</div>
      </div>
    </div>
  </div>

  <div class="footer">
    Generated by Ignitia - AI-Powered Startup Builder<br>
    ${new Date(generation.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
  </div>
</body>
</html>
`

    // Return HTML that can be printed to PDF by the browser
    return new NextResponse(pdfHtml, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `inline; filename="${generation.startup_name.replace(/\s+/g, "-")}-pitch.html"`,
      },
    })
  } catch (error) {
    console.error("Export error:", error)
    return NextResponse.json({ error: "Failed to export PDF" }, { status: 500 })
  }
}
